title: Welcome to my blog!
author: Sanjana Mahmood
email: sanjana.mahmood10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Here you may get to see my achievements and experiences I have made so far. Let's get connected!


# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  smahmood0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
